insert into public.vehicles (
  slug,
  make,
  model,
  year,
  trim,
  category,
  color,
  transmission,
  fuel_type,
  seats,
  daily_rate,
  deposit_amount,
  mileage_limit_per_day,
  extra_mileage_fee,
  currency,
  distance_unit,
  status,
  is_featured,
  description,
  image_urls
)
values
(
  'acura-zdx-2025-white',
  'Acura',
  'ZDX',
  2025,
  'EV',
  'SUV',
  'White',
  'Automatic',
  'Electric',
  5,
  199,
  1750,
  150,
  1.5,
  'USD',
  'miles',
  'available',
  true,
  'EV luxury crossover styling with quiet electric power and a refined cabin feel.',
  array['/assets/fleet/acura-zdx-2025-white-1.jpg', '/assets/fleet/acura-zdx-2025-white-2.jpg', '/assets/fleet/acura-zdx-2025-white-3.jpg', '/assets/fleet/acura-zdx-2025-white-4.jpg', '/assets/fleet/acura-zdx-2025-white-5.jpg']::text[]
),
(
  'bmw-3-series-2026-white',
  'BMW',
  '3 Series',
  2026,
  null,
  'Sedan',
  'White',
  'Automatic',
  'Gas',
  5,
  139,
  1200,
  150,
  1,
  'USD',
  'miles',
  'available',
  true,
  'A sharp premium sedan that balances comfort, handling, and business-ready polish.',
  array['/assets/fleet/bmw-3-series-2026-white-1.jpg', '/assets/fleet/bmw-3-series-2026-white-2.jpg', '/assets/fleet/bmw-3-series-2026-white-3.jpg', '/assets/fleet/bmw-3-series-2026-white-4.jpg', '/assets/fleet/bmw-3-series-2026-white-5.jpg', '/assets/fleet/bmw-3-series-2026-white-6.jpg']::text[]
),
(
  'bmw-4-series-convertible-2026-grey',
  'BMW',
  '4 Series',
  2026,
  'Convertible',
  'Convertible',
  'Grey',
  'Automatic',
  'Gas',
  4,
  189,
  1600,
  150,
  1.5,
  'USD',
  'miles',
  'available',
  true,
  'Open-air coupe energy with premium comfort for coastal drives and nights in Beverly Hills.',
  array['/assets/fleet/bmw-4-series-convertible-2026-grey-1.jpg', '/assets/fleet/bmw-4-series-convertible-2026-grey-2.jpg', '/assets/fleet/bmw-4-series-convertible-2026-grey-3.jpg', '/assets/fleet/bmw-4-series-convertible-2026-grey-4.jpg', '/assets/fleet/bmw-4-series-convertible-2026-grey-5.jpg', '/assets/fleet/bmw-4-series-convertible-2026-grey-6.jpg']::text[]
),
(
  'ford-mustang-2026-white',
  'Ford',
  'Mustang',
  2026,
  null,
  'Coupe',
  'White',
  'Automatic',
  'Gas',
  4,
  179,
  1500,
  150,
  1.5,
  'USD',
  'miles',
  'available',
  true,
  'Classic performance attitude for sunset routes, date nights, and statement arrivals.',
  array['/assets/fleet/ford-mustang-2026-white-1.jpg', '/assets/fleet/ford-mustang-2026-white-2.jpg', '/assets/fleet/ford-mustang-2026-white-3.jpg', '/assets/fleet/ford-mustang-2026-white-4.jpg', '/assets/fleet/ford-mustang-2026-white-5.jpg', '/assets/fleet/ford-mustang-2026-white-6.jpg']::text[]
),
(
  'honda-civic-hybrid-2026-dark-grey',
  'Honda',
  'Civic',
  2026,
  'Hybrid',
  'Sedan',
  'Dark Grey',
  'Automatic',
  'Hybrid',
  5,
  89,
  650,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  true,
  'Efficient, reliable, and easy to park, built for practical daily driving around LA.',
  array['/assets/fleet/honda-civic-hybrid-2026-dark-grey-1.jpg', '/assets/fleet/honda-civic-hybrid-2026-dark-grey-2.jpg', '/assets/fleet/honda-civic-hybrid-2026-dark-grey-3.jpg', '/assets/fleet/honda-civic-hybrid-2026-dark-grey-4.jpg', '/assets/fleet/honda-civic-hybrid-2026-dark-grey-5.jpg', '/assets/fleet/honda-civic-hybrid-2026-dark-grey-6.jpg']::text[]
),
(
  'honda-civic-hybrid-2026-light-grey',
  'Honda',
  'Civic',
  2026,
  'Hybrid',
  'Sedan',
  'Light Grey',
  'Automatic',
  'Hybrid',
  5,
  89,
  650,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  true,
  'Efficient hybrid sedan with a bright modern finish for practical daily drives around LA.',
  array['/assets/fleet/honda-civic-hybrid-2026-light-grey-1.jpg', '/assets/fleet/honda-civic-hybrid-2026-light-grey-2.jpg', '/assets/fleet/honda-civic-hybrid-2026-light-grey-3.jpg', '/assets/fleet/honda-civic-hybrid-2026-light-grey-4.jpg', '/assets/fleet/honda-civic-hybrid-2026-light-grey-5.jpg', '/assets/fleet/honda-civic-hybrid-2026-light-grey-6.jpg']::text[]
),
(
  'hyundai-elantra-2026-grey',
  'Hyundai',
  'Elantra',
  2026,
  null,
  'Sedan',
  'Grey',
  'Automatic',
  'Gas',
  5,
  79,
  500,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  false,
  'A clean economy sedan with modern tech and strong value for longer reservations.',
  array['/assets/fleet/hyundai-elantra-2026-grey-1.jpg', '/assets/fleet/hyundai-elantra-2026-grey-2.jpg', '/assets/fleet/hyundai-elantra-2026-grey-3.jpg', '/assets/fleet/hyundai-elantra-2026-grey-4.jpg', '/assets/fleet/hyundai-elantra-2026-grey-5.jpg', '/assets/fleet/hyundai-elantra-2026-grey-6.jpg']::text[]
),
(
  'jeep-wrangler-willys-2026-blue',
  'Jeep',
  'Wrangler',
  2026,
  'Willys',
  'SUV',
  'Blue',
  'Automatic',
  'Gas',
  5,
  159,
  1250,
  150,
  1,
  'USD',
  'miles',
  'available',
  false,
  'A rugged LA weekend option for beach routes, city cruising, and open-sky drives.',
  array['/assets/fleet/jeep-wrangler-willys-2026-blue-1.jpg', '/assets/fleet/jeep-wrangler-willys-2026-blue-2.jpg', '/assets/fleet/jeep-wrangler-willys-2026-blue-3.jpg', '/assets/fleet/jeep-wrangler-willys-2026-blue-4.jpg', '/assets/fleet/jeep-wrangler-willys-2026-blue-5.jpg', '/assets/fleet/jeep-wrangler-willys-2026-blue-6.jpg']::text[]
),
(
  'lexus-lx-600-2025-white',
  'Lexus',
  'LX 600',
  2025,
  null,
  'SUV',
  'White',
  'Automatic',
  'Gas',
  7,
  249,
  2500,
  150,
  1.5,
  'USD',
  'miles',
  'available',
  false,
  'Full-size luxury SUV with executive space, smooth road manners, and serious presence.',
  array['/assets/fleet/lexus-lx-600-2025-white-1.jpg', '/assets/fleet/lexus-lx-600-2025-white-2.jpg', '/assets/fleet/lexus-lx-600-2025-white-3.jpg', '/assets/fleet/lexus-lx-600-2025-white-4.jpg', '/assets/fleet/lexus-lx-600-2025-white-5.jpg', '/assets/fleet/lexus-lx-600-2025-white-6.jpg']::text[]
),
(
  'mercedes-benz-c300-2026-white',
  'Mercedes-Benz',
  'C300',
  2026,
  null,
  'Sedan',
  'White',
  'Automatic',
  'Gas',
  5,
  169,
  1300,
  150,
  1.5,
  'USD',
  'miles',
  'available',
  false,
  'Modern luxury sedan with executive style, quiet comfort, and premium details.',
  array['/assets/fleet/mercedes-benz-c300-2026-white-1.jpg', '/assets/fleet/mercedes-benz-c300-2026-white-2.jpg', '/assets/fleet/mercedes-benz-c300-2026-white-3.jpg', '/assets/fleet/mercedes-benz-c300-2026-white-4.jpg', '/assets/fleet/mercedes-benz-c300-2026-white-5.jpg']::text[]
),
(
  'nissan-sentra-2026-white',
  'Nissan',
  'Sentra',
  2026,
  null,
  'Sedan',
  'White',
  'Automatic',
  'Gas',
  5,
  75,
  500,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  false,
  'Comfortable daily sedan for guests who want simple, dependable transportation.',
  array['/assets/fleet/nissan-sentra-2026-white-1.jpg', '/assets/fleet/nissan-sentra-2026-white-2.jpg', '/assets/fleet/nissan-sentra-2026-white-3.jpg', '/assets/fleet/nissan-sentra-2026-white-4.jpg']::text[]
),
(
  'toyota-camry-hybrid-2026-blue',
  'Toyota',
  'Camry',
  2026,
  'Hybrid',
  'Sedan',
  'Blue',
  'Automatic',
  'Hybrid',
  5,
  99,
  750,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  false,
  'A smooth midsize hybrid sedan for business trips, family visits, and comfortable commutes.',
  array['/assets/fleet/toyota-camry-hybrid-2026-blue-1.jpg', '/assets/fleet/toyota-camry-hybrid-2026-blue-2.jpg', '/assets/fleet/toyota-camry-hybrid-2026-blue-3.jpg', '/assets/fleet/toyota-camry-hybrid-2026-blue-4.jpg', '/assets/fleet/toyota-camry-hybrid-2026-blue-5.jpg', '/assets/fleet/toyota-camry-hybrid-2026-blue-6.jpg']::text[]
),
(
  'toyota-corolla-2026-grey',
  'Toyota',
  'Corolla',
  2026,
  null,
  'Sedan',
  'Grey',
  'Automatic',
  'Gas',
  5,
  79,
  500,
  150,
  0.75,
  'USD',
  'miles',
  'available',
  false,
  'A trusted compact sedan with low fuel use and easy city handling.',
  array['/assets/fleet/toyota-corolla-2026-grey-1.jpg', '/assets/fleet/toyota-corolla-2026-grey-2.jpg', '/assets/fleet/toyota-corolla-2026-grey-3.jpg', '/assets/fleet/toyota-corolla-2026-grey-4.jpg', '/assets/fleet/toyota-corolla-2026-grey-5.jpg', '/assets/fleet/toyota-corolla-2026-grey-6.jpg']::text[]
),
(
  'volkswagen-tiguan-2025-white',
  'Volkswagen',
  'Tiguan',
  2025,
  null,
  'SUV',
  'White',
  'Automatic',
  'Gas',
  5,
  109,
  900,
  150,
  1,
  'USD',
  'miles',
  'available',
  false,
  'Clean, practical compact SUV for family plans, errands, and longer LA stays.',
  array['/assets/fleet/volkswagen-tiguan-2025-white-1.jpg', '/assets/fleet/volkswagen-tiguan-2025-white-2.jpg', '/assets/fleet/volkswagen-tiguan-2025-white-3.jpg', '/assets/fleet/volkswagen-tiguan-2025-white-4.jpg', '/assets/fleet/volkswagen-tiguan-2025-white-5.jpg', '/assets/fleet/volkswagen-tiguan-2025-white-6.jpg']::text[]
)
on conflict (slug) do update set
  make = excluded.make,
  model = excluded.model,
  year = excluded.year,
  trim = excluded.trim,
  category = excluded.category,
  color = excluded.color,
  transmission = excluded.transmission,
  fuel_type = excluded.fuel_type,
  seats = excluded.seats,
  daily_rate = excluded.daily_rate,
  deposit_amount = excluded.deposit_amount,
  mileage_limit_per_day = excluded.mileage_limit_per_day,
  extra_mileage_fee = excluded.extra_mileage_fee,
  currency = excluded.currency,
  distance_unit = excluded.distance_unit,
  description = excluded.description,
  image_urls = excluded.image_urls,
  updated_at = now();
